# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: James Terry
email: james@jamesterry.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  An exited entrepreneur obsessed with everything product. Working with early stage tech startups to help them through advice, design, development and, occasionally, capital.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jamesterry.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: phatjme
github_username:  phatjme

author: phatjme
twitter:
  username: phatjme
  card: summary
logo: /favicon.png
social:
  name: Adapt
  links:
    - https://twitter.com/phatjme
    - https://www.instagram.com/phatjme
# webmaster_verifications:
  # google: 1234
  # bing: 1234
lang: en_GB

future: true

permalink: /blog/:title

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack
  - README.md 
  - build.sh 
  - package-lock.json
  - package.json

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/css
    - assets/fonts
    - assets/img

sass:
  load_paths: 
    - _sass
    - node_modules
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
